version: "3.9"

services:
  api:
    build: .
    container_name: traffic_api
    ports:
      - "8000:8000"
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SQLITE_DB_FILE=/app/data/traffic.db
      - SELENIUM_URL=http://selenium-hub:4444/wd/hub
      - JWT_SECRET=${JWT_SECRET:-jwt_secret}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-123456}
      - RATE_LIMIT=${RATE_LIMIT:-10/minute}
      - SELENIUM_PROXY=${SELENIUM_PROXY:-}
      - JOBQUEUE_MAX_JOBS=2
      - JOBQUEUE_PER_JOB_CONCURRENCY=20
    volumes:
      - .:/app
      - ./static:/app/static
      - ./data:/app/data

  selenium-hub:
    image: selenium/hub:4.35.0
    container_name: selenium_hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=20           # Maximum concurrent sessions the hub can handle
      - GRID_BROWSER_TIMEOUT=20       # (60) Clean stuck sessions
      - GRID_SESSION_TIMEOUT=90       # Max session duration
      - GRID_TIMEOUT=30
      - GRID_JETTY_MAX_THREADS=100
  chrome:
    image: selenium/node-chrome:124.0
    # container_name: selenium_node_chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4        # 4 sessions per node
      - SE_VNC_ENABLED=false
      - SE_NO_VIRTUAL_PORT=1
      - SE_SESSION_RETRY_INTERVAL=2
      - SE_SESSION_REQUEST_TIMEOUT=30
    shm_size: 1gb
    deploy:
      replicas: 5                     # 5 nodes Ã— 4 sessions = 20 concurrent
